# Configure dependabot to weekly bump all dependencies in Cargo.lock

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      # interval: "weekly"
      interval: daily # for testing purposes (bump.)
      time: "21:00"
      timezone: "America/Denver"
    open-pull-requests-limit: 1
    versioning-strategy: lockfile-only
    # Allow both direct and indirect updates for all packages
    allow:
      - dependency-type: "all"
    # Update all dependencies in a single PR
    groups:
      dependencies:
        patterns:
          - "*"
